---

- name: Manage MecSys Keycloak
  hosts: localhost
  connection: local
  gather_facts: true

  collections:
    - community.general

  tasks:

   - name: Create or update Keycloak realm mecsys
     community.general.keycloak_realm:
       auth_client_id: admin-cli
       auth_keycloak_url: https://kc.mecsys.com.br
       auth_realm: master
       auth_username: "{{ user }}"
       auth_password: "{{ pass }}"
       id: realm
       realm: mecsys
       state: present
       display_name: "MecSys keycloak Realm."
   