---

- name: My first play
  hosts: localhost
  tasks:

   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world

   - name: Nmap inventory
     community.general.nmap:
      address: gw.mecsys.com.br
