---

- name: Install Python Modules for Semaphore
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:

  - name: Install requirements
    ansible.builtin.pip:
      requirements: '/home/semaphore/requirements.txt'
      extra_args: '--user --upgrade'
    become_user: 'semaphore'
